sudo: true
dist: trusty
addons:
language: node_js
node_js:
    - "10"
    - "12"
    - "14"
before_script:
    - npm run lint
after_script:
    - npm run coveralls
git:
    depth: 10
cache:
    yarn: true
